# /home/fabio/Documentos/Projetos/portfolio/mkdocs.yml
site_name: Meu Portfólio
nav:
  - Início: index.md
  - Projetos:
      - Curso de WebLogic 12c: ../curso-weblogic-12c/README.md
      - Curso de Python: ../curso-python/README.md
theme:
  name: material

