site_name: Portfólio Estudosecursos
nav:
  - Início: index.md
  - Sobre: about.md
  - Experiência: experiencia.md
  - Currículo: curriculo.md
  - Projetos:
      - Golang: projects/curso-golang.md
      - Python: projects/curso-python.md
      - Weblogic 12c: projects/curso-weblogic-12c.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - toc.integrate
  palette:
    scheme: default
    primary: deep purple
    accent: indigo  
