---

## portfolio/.github/workflows/deploy.yml
#yaml

```yaml
# portfolio/.github/workflows/deploy.yml

name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Build do site
        run: mkdocs build --strict

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
